--- 
title: "Measuring what Matters: Introduction to Rasch Analysis in R"
#author: "Exercise and data: Anthony Clairmont; Assistance, web: Daniel Katz; Direction: Mike Wilton"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: ref.bib
biblio-style: apalike
link-citations: yes
description: "This book is meant to be used as a guide for getting started using the Rasch model"
---

# Introduction
This is meant to be a general introduction to using the Rasch model for constructing measures in R. The book is meant to get you started but is by no means where you should stop. Please see, @WilsonMark2005 and @BondTrevor for more. To get started, move to the next chapter. For an extremely brief overview, read below.

The Rasch model is based on a theory of measurement. Whereas one may typically fine-tune a model to fit the data, in the Rasch paradigm, one compares the data to the Rasch model. Under this view, when the data does not fit the Rasch model, it is believed that the data may not be suitable for measurement. 

Sometimes it is said that Rasch is difficult or unrealistic to work with because of its assumptions about the underlying data structure. However, these are not assumptions like the assumptions of ordinary least squares (OLS or linear regression). Instead, these "assumptions" - that the data fit the Rasch model - are the very things we are interested in testing to see if our data is suitable for measurement. If we deem that it is, we may proceed to use the results. If we deem that it is not, all is not lost. We can take that information to alter our items, theory, or model.

There are often two lines of objections to the Rasch model. One line says that data conforming to the Rasch model does guarantee measurement. That is, the Rasch model itself is not a form of measurement. For more on this view, see the work of Joel Michell. Another objection says that the form of additive measurement for which the users of Rasch measurement advocate is not the only form of measurement. Estimates derived from other models can be considered measurement. For a wider view on Item Response Theory (IRT), including more on this latter view, see Embretson & Reise (2004)

For questions, comments, and feedback, please contact:

Danny Katz -
dkatz@ucsb.edu


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
